# Generated by Django 3.2.25 on 2024-09-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20240910_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='programmes',
            field=models.ManyToManyField(related_name='courses', to='app.Programme'),
        ),
    ]
